### ISSUE TITLE
aws cli installation issue

### ISSUE THREAD

**Issue by volomatt** [CircleCI-Public/aws-ecr-orb#44]
### Orb version

6.1.0

### What happened

#!/bin/bash -eo pipefail
aws configure set aws_access_key_id \
$AWS_ACCESS_KEY_ID \
--profile default
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/2.7.12/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/awscli/clidriver.py", line 36, in <module>
    from awscli.help import ProviderHelpCommand
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/awscli/help.py", line 20, in <module>
    from docutils.core import publish_string
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/docutils/core.py", line 246
    print('\n::: Runtime settings:', file=self._stderr)
                                         ^
SyntaxError: invalid syntax
Exited with code 1

### Expected behavior

AWS would configure its credentials

**Comment by volomatt** [comment]
Tracked it down to aws-cli 
https://github.com/aws/aws-cli/issues/4332
